### ISSUE TITLE
Error de consumo de api

### ISSUE THREAD

**Issue by serome111** [nequibc/nequi-api-client-php#2]
Estoy haciendo el ejemplo, pongo las keys en la configuración y procedo a ejecutar y me lanza un error
 
![image](https://user-images.githubusercontent.com/32885503/53191902-1355a280-35db-11e9-8338-b9d5c64c7eb5.png)

Luego intentó acceder a  la web de http://developers.nequi.com.co
y me parece que aun no esta en funcionamiento
que procede para poder utilizar su servicio y saber como solucionar mi error 

![image](https://user-images.githubusercontent.com/32885503/53191823-dc7f8c80-35da-11e9-8790-1baee5429cfd.png)

**Comment by nequibc** [comment]
Buenos dias,

Espero estes bien,

El primer error significa que estas ingresando las keys incorrectamente, fíjate no tengan espacios y esten asignadas al valor correcto.

La web http://developers.nequi.com.co se migro a http://conecta.nequi.com.co.

Gracias,

Saludos,

**Comment by serome111** [comment]
efectivamente lo he verificado y se encuentran asignadas tal cual, y no tiene espacios ni caracteres especiales intermedios y como te puedes fijar ya la tengo activa
![image](https://user-images.githubusercontent.com/32885503/53740442-30536680-3e62-11e9-91b3-33395d9efbec.png)
